//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teo4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaccion
    {
        public int Id { get; set; }
        public int tipoDocumento { get; set; }
        public string documento { get; set; }
        public decimal monto { get; set; }
        public string debitoCredito { get; set; }
        public int tipoTransaccion { get; set; }
        public System.DateTime fechaTransaccion { get; set; }
        public string descripcion { get; set; }
        public string oficina { get; set; }
    }
}
