//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teo6ConsumirWebService.SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://intec.edu.do")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://intec.edu.do")]
    [System.SerializableAttribute()]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        private int TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intec.edu.do", ConfigurationName="SR.ServicioWebTeo6Soap")]
    public interface ServicioWebTeo6Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://intec.edu.do no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/HelloWorld", ReplyAction="*")]
        Teo6ConsumirWebService.SR.HelloWorldResponse HelloWorld(Teo6ConsumirWebService.SR.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Teo6ConsumirWebService.SR.HelloWorldResponse> HelloWorldAsync(Teo6ConsumirWebService.SR.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/Sumar", ReplyAction="*")]
        int Sumar(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumarAsync(int num1, int num2);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://intec.edu.do no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RegistrarCliente", ReplyAction="*")]
        Teo6ConsumirWebService.SR.RegistrarClienteResponse RegistrarCliente(Teo6ConsumirWebService.SR.RegistrarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RegistrarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Teo6ConsumirWebService.SR.RegistrarClienteResponse> RegistrarClienteAsync(Teo6ConsumirWebService.SR.RegistrarClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://intec.edu.do", Order=0)]
        public Teo6ConsumirWebService.SR.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Teo6ConsumirWebService.SR.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://intec.edu.do", Order=0)]
        public Teo6ConsumirWebService.SR.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Teo6ConsumirWebService.SR.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarCliente", Namespace="http://intec.edu.do", Order=0)]
        public Teo6ConsumirWebService.SR.RegistrarClienteRequestBody Body;
        
        public RegistrarClienteRequest() {
        }
        
        public RegistrarClienteRequest(Teo6ConsumirWebService.SR.RegistrarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class RegistrarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Teo6ConsumirWebService.SR.Cliente cliente;
        
        public RegistrarClienteRequestBody() {
        }
        
        public RegistrarClienteRequestBody(Teo6ConsumirWebService.SR.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarClienteResponse", Namespace="http://intec.edu.do", Order=0)]
        public Teo6ConsumirWebService.SR.RegistrarClienteResponseBody Body;
        
        public RegistrarClienteResponse() {
        }
        
        public RegistrarClienteResponse(Teo6ConsumirWebService.SR.RegistrarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class RegistrarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Teo6ConsumirWebService.SR.Mensaje RegistrarClienteResult;
        
        public RegistrarClienteResponseBody() {
        }
        
        public RegistrarClienteResponseBody(Teo6ConsumirWebService.SR.Mensaje RegistrarClienteResult) {
            this.RegistrarClienteResult = RegistrarClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebTeo6SoapChannel : Teo6ConsumirWebService.SR.ServicioWebTeo6Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebTeo6SoapClient : System.ServiceModel.ClientBase<Teo6ConsumirWebService.SR.ServicioWebTeo6Soap>, Teo6ConsumirWebService.SR.ServicioWebTeo6Soap {
        
        public ServicioWebTeo6SoapClient() {
        }
        
        public ServicioWebTeo6SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebTeo6SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebTeo6SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebTeo6SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teo6ConsumirWebService.SR.HelloWorldResponse Teo6ConsumirWebService.SR.ServicioWebTeo6Soap.HelloWorld(Teo6ConsumirWebService.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Teo6ConsumirWebService.SR.HelloWorldRequest inValue = new Teo6ConsumirWebService.SR.HelloWorldRequest();
            inValue.Body = new Teo6ConsumirWebService.SR.HelloWorldRequestBody();
            Teo6ConsumirWebService.SR.HelloWorldResponse retVal = ((Teo6ConsumirWebService.SR.ServicioWebTeo6Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teo6ConsumirWebService.SR.HelloWorldResponse> Teo6ConsumirWebService.SR.ServicioWebTeo6Soap.HelloWorldAsync(Teo6ConsumirWebService.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teo6ConsumirWebService.SR.HelloWorldResponse> HelloWorldAsync() {
            Teo6ConsumirWebService.SR.HelloWorldRequest inValue = new Teo6ConsumirWebService.SR.HelloWorldRequest();
            inValue.Body = new Teo6ConsumirWebService.SR.HelloWorldRequestBody();
            return ((Teo6ConsumirWebService.SR.ServicioWebTeo6Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Sumar(int num1, int num2) {
            return base.Channel.Sumar(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> SumarAsync(int num1, int num2) {
            return base.Channel.SumarAsync(num1, num2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teo6ConsumirWebService.SR.RegistrarClienteResponse Teo6ConsumirWebService.SR.ServicioWebTeo6Soap.RegistrarCliente(Teo6ConsumirWebService.SR.RegistrarClienteRequest request) {
            return base.Channel.RegistrarCliente(request);
        }
        
        public Teo6ConsumirWebService.SR.Mensaje RegistrarCliente(Teo6ConsumirWebService.SR.Cliente cliente) {
            Teo6ConsumirWebService.SR.RegistrarClienteRequest inValue = new Teo6ConsumirWebService.SR.RegistrarClienteRequest();
            inValue.Body = new Teo6ConsumirWebService.SR.RegistrarClienteRequestBody();
            inValue.Body.cliente = cliente;
            Teo6ConsumirWebService.SR.RegistrarClienteResponse retVal = ((Teo6ConsumirWebService.SR.ServicioWebTeo6Soap)(this)).RegistrarCliente(inValue);
            return retVal.Body.RegistrarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teo6ConsumirWebService.SR.RegistrarClienteResponse> Teo6ConsumirWebService.SR.ServicioWebTeo6Soap.RegistrarClienteAsync(Teo6ConsumirWebService.SR.RegistrarClienteRequest request) {
            return base.Channel.RegistrarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teo6ConsumirWebService.SR.RegistrarClienteResponse> RegistrarClienteAsync(Teo6ConsumirWebService.SR.Cliente cliente) {
            Teo6ConsumirWebService.SR.RegistrarClienteRequest inValue = new Teo6ConsumirWebService.SR.RegistrarClienteRequest();
            inValue.Body = new Teo6ConsumirWebService.SR.RegistrarClienteRequestBody();
            inValue.Body.cliente = cliente;
            return ((Teo6ConsumirWebService.SR.ServicioWebTeo6Soap)(this)).RegistrarClienteAsync(inValue);
        }
    }
}
