//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab06Consola.SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Verdugo", Namespace="http://intec.edu.do/")]
    [System.SerializableAttribute()]
    public partial class Verdugo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        private System.DateTime FechaNacimientoField;
        
        private System.DateTime FechaEventoField;
        
        private int CantidadHijosField;
        
        private bool VivoField;
        
        private bool PresoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaEvento {
            get {
                return this.FechaEventoField;
            }
            set {
                if ((this.FechaEventoField.Equals(value) != true)) {
                    this.FechaEventoField = value;
                    this.RaisePropertyChanged("FechaEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int CantidadHijos {
            get {
                return this.CantidadHijosField;
            }
            set {
                if ((this.CantidadHijosField.Equals(value) != true)) {
                    this.CantidadHijosField = value;
                    this.RaisePropertyChanged("CantidadHijos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Vivo {
            get {
                return this.VivoField;
            }
            set {
                if ((this.VivoField.Equals(value) != true)) {
                    this.VivoField = value;
                    this.RaisePropertyChanged("Vivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool Preso {
            get {
                return this.PresoField;
            }
            set {
                if ((this.PresoField.Equals(value) != true)) {
                    this.PresoField = value;
                    this.RaisePropertyChanged("Preso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Indicios", Namespace="http://intec.edu.do/")]
    [System.SerializableAttribute()]
    public partial class Indicios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://intec.edu.do/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        private int TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intec.edu.do/", ConfigurationName="SR.servicio_lab6Soap")]
    public interface servicio_lab6Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://intec.edu.do/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/HelloWorld", ReplyAction="*")]
        Lab06Consola.SR.HelloWorldResponse HelloWorld(Lab06Consola.SR.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab06Consola.SR.HelloWorldResponse> HelloWorldAsync(Lab06Consola.SR.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento verdugo del espacio de nombres http://intec.edu.do/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RegistrarVerdugoIndicio", ReplyAction="*")]
        Lab06Consola.SR.RegistrarVerdugoIndicioResponse RegistrarVerdugoIndicio(Lab06Consola.SR.RegistrarVerdugoIndicioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RegistrarVerdugoIndicio", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab06Consola.SR.RegistrarVerdugoIndicioResponse> RegistrarVerdugoIndicioAsync(Lab06Consola.SR.RegistrarVerdugoIndicioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://intec.edu.do/", Order=0)]
        public Lab06Consola.SR.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Lab06Consola.SR.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://intec.edu.do/", Order=0)]
        public Lab06Consola.SR.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Lab06Consola.SR.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarVerdugoIndicioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarVerdugoIndicio", Namespace="http://intec.edu.do/", Order=0)]
        public Lab06Consola.SR.RegistrarVerdugoIndicioRequestBody Body;
        
        public RegistrarVerdugoIndicioRequest() {
        }
        
        public RegistrarVerdugoIndicioRequest(Lab06Consola.SR.RegistrarVerdugoIndicioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do/")]
    public partial class RegistrarVerdugoIndicioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab06Consola.SR.Verdugo verdugo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Lab06Consola.SR.Indicios indicio;
        
        public RegistrarVerdugoIndicioRequestBody() {
        }
        
        public RegistrarVerdugoIndicioRequestBody(Lab06Consola.SR.Verdugo verdugo, Lab06Consola.SR.Indicios indicio) {
            this.verdugo = verdugo;
            this.indicio = indicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarVerdugoIndicioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarVerdugoIndicioResponse", Namespace="http://intec.edu.do/", Order=0)]
        public Lab06Consola.SR.RegistrarVerdugoIndicioResponseBody Body;
        
        public RegistrarVerdugoIndicioResponse() {
        }
        
        public RegistrarVerdugoIndicioResponse(Lab06Consola.SR.RegistrarVerdugoIndicioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do/")]
    public partial class RegistrarVerdugoIndicioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab06Consola.SR.Respuesta RegistrarVerdugoIndicioResult;
        
        public RegistrarVerdugoIndicioResponseBody() {
        }
        
        public RegistrarVerdugoIndicioResponseBody(Lab06Consola.SR.Respuesta RegistrarVerdugoIndicioResult) {
            this.RegistrarVerdugoIndicioResult = RegistrarVerdugoIndicioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicio_lab6SoapChannel : Lab06Consola.SR.servicio_lab6Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicio_lab6SoapClient : System.ServiceModel.ClientBase<Lab06Consola.SR.servicio_lab6Soap>, Lab06Consola.SR.servicio_lab6Soap {
        
        public servicio_lab6SoapClient() {
        }
        
        public servicio_lab6SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicio_lab6SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicio_lab6SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicio_lab6SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab06Consola.SR.HelloWorldResponse Lab06Consola.SR.servicio_lab6Soap.HelloWorld(Lab06Consola.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Lab06Consola.SR.HelloWorldRequest inValue = new Lab06Consola.SR.HelloWorldRequest();
            inValue.Body = new Lab06Consola.SR.HelloWorldRequestBody();
            Lab06Consola.SR.HelloWorldResponse retVal = ((Lab06Consola.SR.servicio_lab6Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab06Consola.SR.HelloWorldResponse> Lab06Consola.SR.servicio_lab6Soap.HelloWorldAsync(Lab06Consola.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab06Consola.SR.HelloWorldResponse> HelloWorldAsync() {
            Lab06Consola.SR.HelloWorldRequest inValue = new Lab06Consola.SR.HelloWorldRequest();
            inValue.Body = new Lab06Consola.SR.HelloWorldRequestBody();
            return ((Lab06Consola.SR.servicio_lab6Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab06Consola.SR.RegistrarVerdugoIndicioResponse Lab06Consola.SR.servicio_lab6Soap.RegistrarVerdugoIndicio(Lab06Consola.SR.RegistrarVerdugoIndicioRequest request) {
            return base.Channel.RegistrarVerdugoIndicio(request);
        }
        
        public Lab06Consola.SR.Respuesta RegistrarVerdugoIndicio(Lab06Consola.SR.Verdugo verdugo, Lab06Consola.SR.Indicios indicio) {
            Lab06Consola.SR.RegistrarVerdugoIndicioRequest inValue = new Lab06Consola.SR.RegistrarVerdugoIndicioRequest();
            inValue.Body = new Lab06Consola.SR.RegistrarVerdugoIndicioRequestBody();
            inValue.Body.verdugo = verdugo;
            inValue.Body.indicio = indicio;
            Lab06Consola.SR.RegistrarVerdugoIndicioResponse retVal = ((Lab06Consola.SR.servicio_lab6Soap)(this)).RegistrarVerdugoIndicio(inValue);
            return retVal.Body.RegistrarVerdugoIndicioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab06Consola.SR.RegistrarVerdugoIndicioResponse> Lab06Consola.SR.servicio_lab6Soap.RegistrarVerdugoIndicioAsync(Lab06Consola.SR.RegistrarVerdugoIndicioRequest request) {
            return base.Channel.RegistrarVerdugoIndicioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab06Consola.SR.RegistrarVerdugoIndicioResponse> RegistrarVerdugoIndicioAsync(Lab06Consola.SR.Verdugo verdugo, Lab06Consola.SR.Indicios indicio) {
            Lab06Consola.SR.RegistrarVerdugoIndicioRequest inValue = new Lab06Consola.SR.RegistrarVerdugoIndicioRequest();
            inValue.Body = new Lab06Consola.SR.RegistrarVerdugoIndicioRequestBody();
            inValue.Body.verdugo = verdugo;
            inValue.Body.indicio = indicio;
            return ((Lab06Consola.SR.servicio_lab6Soap)(this)).RegistrarVerdugoIndicioAsync(inValue);
        }
    }
}
